version: '3'
services:
  database:
    container_name: postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db_social
    ports:
      - '5432:5432'
    restart: unless-stopped

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - database
